version: '3.9'
services:
  web:
    container_name: api
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ..:/usr/share/nginx/api
      - ./nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./npm:/root/.npm/_logs/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    working_dir: /usr/share/nginx/api
    
    networks:
      - db_default
networks:
  db_default:
    external: true